//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinestore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int con_id { get; set; }
        public string con_name { get; set; }
        public string con_email { get; set; }
        public string con_number { get; set; }
        public string con_msg { get; set; }
    }
}
