//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinestore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.logins = new HashSet<login>();
        }
    
        public int j_id { get; set; }
        public Nullable<int> j_fk_vacan { get; set; }
        public string j_fullname { get; set; }
        public string j_email { get; set; }
        public string j_number { get; set; }
        public string j_city { get; set; }
        public string j_country { get; set; }
        public string j_address { get; set; }
        public string j_qualification { get; set; }
        public string j_experince { get; set; }
        public string j_gander { get; set; }
        public Nullable<System.DateTime> j_age { get; set; }
    
        public virtual vacanci vacanci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login> logins { get; set; }
    }
}
