//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinestore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.carts = new HashSet<cart>();
            this.comments = new HashSet<comment>();
        }
    
        public int pro_id { get; set; }
        public Nullable<int> pro_fk_cat1 { get; set; }
        public Nullable<int> pro_fk_cat2 { get; set; }
        public string pro_title { get; set; }
        public Nullable<int> pro_price { get; set; }
        public string pro_discrip { get; set; }
        public string pro_img { get; set; }
        public Nullable<decimal> pro_oldprice { get; set; }
        public string pro_brand { get; set; }
        public Nullable<int> pro_qty { get; set; }
        public string pro_img2 { get; set; }
        public string pro_img3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        public virtual category1 category1 { get; set; }
        public virtual category2 category2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
    }
}
